import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DarkmodeProvider from "@/Context/DarkMode";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkmodeProvider>
          {children}
        </DarkmodeProvider>
      </body>
    </html>
  );
}
